services:
    postgres:
        container_name: site-builder-db
        image: postgres:16
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: site-builder-test
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "6000:5432"
volumes:
    postgres_data:
