services:
    app:
        container_name: site-builder-app
        build:
            context: .
            args:
                DATABASE_URL: "postgresql://postgres:postgres@host.docker.internal:6000/site-builder-test?schema=public&connect_timeout=60"
        ports:
            - "3000:3000"
