name: Deploy to VPS

on:
    push:
        branches:
            - main

jobs:
    main:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to VPS
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  port: 22
            - name: Use Node.js 20
              uses: actions/setup-node@v2
              with:
                  node-version: 20.x
            - name: Enter dir
              run: cd /root/domains/site-builder.dominikkoniarz.pl/
            - name: Git pull
              run: git pull
            - name: Install dependencies
              run: |
                  pnpm -v
                  pnpm install
            - name: Build
              run: pnpm run build
            - name: Start
              run: pm2 start ecosystem.config.js
